/**
 * Legacy URL aliases → canonical paths (exact match on pathname only).
 * Lookup key is pathname.toLowerCase(); redirect only when pathname !== destination.
 *
 * High-traffic marketing routes canonicalize to **lowercase** (see
 * `lib/canonical-path-case.ts` + middleware rewrite to PascalCase folders).
 * Blog stays `/Blog` (case-insensitive FS / historical redirect safety).
 */
export const LEGACY_EXACT_REDIRECTS: Record<string, string> = {
  '/about': '/about',
  '/contact': '/contact',
  '/faq': '/faq',
  '/cookies': '/cookies',
  '/privacy': '/privacy',
  '/terms': '/terms',
  '/gdpr': '/gdpr',
  '/map': '/map',
  '/wiki': '/wiki',
  '/premium': '/premium',
  '/join': '/join',
  '/whatsapp': '/whatsapp',
  '/pace': '/pace',
  '/ico': '/ico',
  '/blog': '/Blog',
  '/accessibility': '/accessibility',
  '/complaints': '/complaints',
  '/dataprotection': '/dataprotection',
  '/formslibrary': '/formslibrary',
  '/forum': '/forum',
  '/firms': '/legal-services-directory/category/solicitors',
  '/forces': '/forces',
  '/home': '/',
  '/f-a-q': '/faq',
  '/g-d-p-r': '/gdpr',
  '/termsandconditions': '/terms',
  '/terms-and-conditions': '/terms',
  '/howtobecome': '/howtobecome',
  '/getwork': '/getwork',
  '/findsupervisingsolicitor': '/findsupervisingsolicitor',
  '/howtofindsupervisingsolicitor': '/findsupervisingsolicitor',
  '/gofeatured': '/gofeatured',
  '/escapefeecalculator': '/escapefeecalculator',
  '/policestationrates': '/policestationrates',
  '/policestationreppay': '/policestationreppay',
  '/policestationrepjobsuk': '/policestationrepjobsuk',
  '/stationsdirectory': '/stationsdirectory',
  '/helpusstationnumbers': '/helpusstationnumbers',
  '/help-us-station-numbers': '/helpusstationnumbers',
  '/whatdoesrepdo': '/whatdoesrepdo',
  '/dutysolicitorvsrep': '/dutysolicitorvsrep',
  '/beginnersguide': '/beginnersguide',
  '/commonoffencesguide': '/commonoffencesguide',
  '/interviewundercaution': '/interviewundercaution',
  '/policedisclosureguide': '/policedisclosureguide',
  '/magistratescourtfees': '/magistratescourtfees',
  '/crowncourtfees': '/crowncourtfees',
  '/gettingstarted': '/gettingstarted',
  '/resources': '/resources',
  '/legalupdates': '/legalupdates',
  '/policestationrepsbycounty': '/policestationrepsbycounty',
  '/solicitorpolicestationcoveruk': '/solicitorpolicestationcoveruk',
  '/buildportfolioguide': '/buildportfolioguide',
  '/criminallawcareerguide': '/criminallawcareerguide',
  '/prepareforcit': '/prepareforcit',
  '/aboutfounder': '/aboutfounder',
  '/kentpolicestationreps': '/kentpolicestationreps',
  '/repfaqmaster': '/repfaqmaster',
  '/subscribe': '/subscribe',
  '/account': '/account',
  '/profile': '/profile',
  '/login': '/account',
  '/sign-in': '/account',
  '/custodynote': '/custodynote',
  '/rep/joanna-wayne': '/rep/joanne-wayne',
  '/guided-assistant': '/ai-assistant',
};
