/** Police forces listed on `/Forces` (territorial + BTP + MoD). */
export const UK_POLICE_FORCES = [
  'Avon and Somerset Constabulary',
  'Bedfordshire Police',
  'British Transport Police',
  'Cambridgeshire Constabulary',
  'Cheshire Constabulary',
  'City of London Police',
  'Cleveland Police',
  'Cumbria Constabulary',
  'Derbyshire Constabulary',
  'Devon and Cornwall Police',
  'Dorset Police',
  'Durham Constabulary',
  'Dyfed-Powys Police',
  'Essex Police',
  'Gloucestershire Constabulary',
  'Greater Manchester Police',
  'Gwent Police',
  'Hampshire Constabulary',
  'Hertfordshire Constabulary',
  'Humberside Police',
  'Kent Police',
  'Lancashire Constabulary',
  'Leicestershire Police',
  'Lincolnshire Police',
  'Merseyside Police',
  'Metropolitan Police',
  'Ministry of Defence Police',
  'Norfolk Constabulary',
  'North Wales Police',
  'North Yorkshire Police',
  'Northamptonshire Police',
  'Northumbria Police',
  'Nottinghamshire Police',
  'South Wales Police',
  'South Yorkshire Police',
  'Staffordshire Police',
  'Suffolk Constabulary',
  'Surrey Police',
  'Sussex Police',
  'Thames Valley Police',
  'Warwickshire Police',
  'West Mercia Police',
  'West Midlands Police',
  'West Yorkshire Police',
  'Wiltshire Police',
] as const;

export const UK_POLICE_FORCES_COUNT = UK_POLICE_FORCES.length;
